safe:      true
permalink: pretty
highlighter: pygments
markdown:  redcarpet
exclude:   [ README.md, Gemfile, vendor, .*, bower.json ]
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
sass:
    sass_dir: _sass
# Setup
title:               Achref Tlili
tagline:
description:         'Achref Tlili Blog for web development'
url:                 https://achreftlili.github.io/
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Mark Otto
  url:               https://achreftlili.github.io/about/
  email:             tliliachref1990@gmail.com

# Custom vars
version:             1.0.0
